### ISSUE TITLE
Don't know how to build task 'textcaptcha:config'

### ISSUE THREAD

**Issue by ghost** [matthutchinson/acts_as_textcaptcha#27]
Anybody else getting this? Using Rails 6. Thanks!

**Comment by matthutchinson** [comment]
I’ll take a look, I haven’t had time to test on Rails 6 yet, 😐

**Comment by anonymous-donor** [comment]
Thanks @matthutchinson!

I forgot to include my Gist which shows the form field not showing up at all:

https://gist.github.com/anonymous-donor/7ec3687085b9ab6b64f6cc8f986e83a2

Cheers!

**Comment by anonymous-donor** [comment]
@matthutchinson I could upload a test app if you wanna save some time?

**Comment by matthutchinson** [comment]
Solved in commit [56040](https://github.com/matthutchinson/acts_as_textcaptcha/commit/56040728bba0aac81b05068607abbe7be2affc28) with `4.5.1` released today.
