### ISSUE TITLE
Add `config.cache_store = :memory_store` to documentation

### ISSUE THREAD

**Issue by ratahtatah** [matthutchinson/acts_as_textcaptcha#28]
Add the need to set `config.cache_store = :null_store` to `config.cache_store = :memory_store` in `config/environments/development.rb`, won't work otherwise. Thanks!

**Comment by matthutchinson** [comment]
Thanks for reminding me 👍 

Closing with [this commit](https://github.com/matthutchinson/acts_as_textcaptcha/commit/e40e8472321cdda3f3d354443905b5f5596d1c93).
